project:
  type: website
  output-dir: docs

website:
  title: "UMAIR BIN SAAD - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
          - href: https://zyang91.github.io/PPA_portfolio/lab/lab_0/
            text: "Lab 0: dplyr Basics"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
